apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    {{- include "voting-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: db
  annotations:
    {{- include "voting-app.syncWave" "1" | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: db
      port: {{ .Values.db.service.port }}
      targetPort: postgres
  selector:
    {{- include "voting-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: db
