apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "voting-app.fullname" . }}-postgres
  labels:
    {{- include "voting-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: db
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    kind: {{ .Values.externalSecret.secretStore.kind }}
    name: {{ .Values.externalSecret.secretStore.name }}
  target:
    name: {{ include "voting-app.postgresSecretName" . }}
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: username
      remoteRef:
        key: {{ .Values.externalSecret.remoteKey }}
        property: {{ .Values.externalSecret.properties.username }}
    - secretKey: password
      remoteRef:
        key: {{ .Values.externalSecret.remoteKey }}
        property: {{ .Values.externalSecret.properties.password }}
    - secretKey: root-password
      remoteRef:
        key: {{ .Values.externalSecret.remoteKey }}
        property: {{ .Values.externalSecret.properties.rootPassword }}
