{{- if .Values.db.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "voting-app.fullname" . }}-postgres
  labels:
    {{- include "voting-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: db
  annotations:
    {{- include "voting-app.syncWave" "0" | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.db.persistence.accessMode }}
  storageClassName: {{ .Values.db.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.db.persistence.size }}
{{- end }}
{{- if .Values.redis.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "voting-app.fullname" . }}-redis
  labels:
    {{- include "voting-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
  annotations:
    {{- include "voting-app.syncWave" "0" | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.redis.persistence.accessMode }}
  storageClassName: {{ .Values.redis.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.redis.persistence.size }}
{{- end }}
