apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    {{- include "voting-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
  annotations:
    {{- include "voting-app.syncWave" "1" | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: {{ .Values.redis.service.port }}
      targetPort: redis
  selector:
    {{- include "voting-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
