apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "voting-app.fullname" . }}-result
  labels:
    {{- include "voting-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: result
spec:
  replicas: {{ .Values.result.replicaCount }}
  selector:
    matchLabels:
      {{- include "voting-app.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: result
  template:
    metadata:
      labels:
        {{- include "voting-app.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: result
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: result
          image: {{ include "voting-app.image" (dict "root" . "component" .Values.result) }}
          imagePullPolicy: {{ .Values.result.image.pullPolicy }}
          ports:
            - name: result
              containerPort: 80
