apiVersion: v1
kind: Service
metadata:
  name: {{ include "voting-app.fullname" . }}-result
  labels:
    {{- include "voting-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: result
  annotations:
    {{- include "voting-app.syncWave" "2" | nindent 4 }}
spec:
  type: {{ .Values.result.service.type }}
  ports:
    - name: result
      port: {{ .Values.result.service.port }}
      targetPort: result
      {{- if and (eq .Values.result.service.type "NodePort") .Values.result.service.nodePort }}
      nodePort: {{ .Values.result.service.nodePort }}
      {{- end }}
  selector:
    {{- include "voting-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: result
