apiVersion: v1
kind: Service
metadata:
  name: {{ include "voting-app.fullname" . }}-vote
  labels:
    {{- include "voting-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: vote
  annotations:
    {{- include "voting-app.syncWave" "2" | nindent 4 }}
spec:
  type: {{ .Values.vote.service.type }}
  ports:
    - name: vote
      port: {{ .Values.vote.service.port }}
      targetPort: vote
      {{- if and (eq .Values.vote.service.type "NodePort") .Values.vote.service.nodePort }}
      nodePort: {{ .Values.vote.service.nodePort }}
      {{- end }}
  selector:
    {{- include "voting-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: vote
